### ISSUE TITLE
Logo Animation isn't centered properly.

### ISSUE THREAD

**Issue by vikas-0** [vikas-0/TechTrix2017_Website#4]
I tried percentage margin. Also tried setting margin by javascript dynamically. But none is helping on higher resolution

**Comment by joas8211** [comment]
Hey!
You just need to remove all the margins and set `margin: auto;` for your logo.
```css
#logoAnime {
    position: relative;
    height: 350px;
    width: 350px;
    margin: auto;
}
```
Added pull request #5 to fix the issue.
